### ISSUE TITLE
Link fragments to point to specific extension no longer work

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/website#1048]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

Open any of our past links that point to a specific extension to download
Example
https://tachiyomi.org/extensions/#all.mangadex

### Expected behavior

The link should open the extensions page and filter out the extension mentioned in the link fragment

### Actual behavior

The extension page just loads and doesnt filter anything

### Other details

Its a less frequently used feature so took me a while to notice it was broken

**Comment by Soitora** [comment]
How it worked before it's that it just scrolled to the extension, I don't remember it filtering the others out

That being said, I'm not really sure what method to fix that with

**Comment by kiriya-aoi** [comment]
Seems to work as expected (jumping) on Vivaldi mobile and Vivaldi desktop on my devices, haven't tested on anything else yet. It does scroll to the extension _after_ the target though, putting the target off screen.

**Comment by curche** [comment]
Seems like it works on stable firefox for android... sometimes, i.e.

Most notably, the extension is not getting highlighted properly always which made it more confusing 
and the entire thing generally takes longer than before so if the user starts interacting with the website before that, it stops trying to point to the extension midway

> I don't remember it filtering the others out

I was sure it did that... paging @ghostbear to confirm how the link worked previously.

**Comment by alessandrojean** [comment]
Previously it replaced the `window.location`, but this isn't very recommended as VitePress uses Vue router. I can take a look when I have some time.

**Comment by arkon** [comment]
Should also note that there needs to be a scroll offset added since when it _does_ work, the desired target is under the header.
