### ISSUE TITLE
To many requests 

### ISSUE THREAD

**Issue by ZaMaou** [tachiyomiorg/website#1050]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1- I migrated one manga for the extension Golden Mangás
2- Entered on manga screen there's no chapters 
3- shows the message java.net.ProtocolException

### Expected behavior

I expected that i can read mangas on the extension Golden Mangás because it is the only good PT-BR extension 

### Actual behavior

I cannot use it

### Other details

![Screenshot_20230923-142632](https://github.com/tachiyomiorg/website/assets/126201255/b3b3bbf7-d1a9-476d-8386-b60e0d2c8e58)
A example

**Comment by Seishirou101** [comment]
This is not the right repo.
