### ISSUE TITLE
A fix for nhentai cloud flare

### ISSUE THREAD

**Issue by Jakcel** [tachiyomiorg/website#1062]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

If you change the default user agent string on tachiyomi to
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44 Nhentai now works

### Other details

![Screenshot_20231002-103529](https://github.com/tachiyomiorg/website/assets/146752455/422286b4-9ab9-47b3-b87f-f166ac560472)

![Screenshot_20231002-103443](https://github.com/tachiyomiorg/website/assets/146752455/4d918789-474b-47c3-8ac7-b9f18e471487)

**Comment by Seishirou101** [comment]
what may work for you may not work for someone else, changing ua is already on the website.

**Comment by Jakcel** [comment]
Yes but I'm talking about as the default user agent as I am both on Android 11 and 12  and works on both, but yes I do agree it may not work for others. it's just the defaulted user agent on tachiyomiAZ and it works so I wanted to be helpful
