### ISSUE TITLE
Need Account for tachiyomi

### ISSUE THREAD

**Issue by cruelninja** [tachiyomiorg/website#1091]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Sign In 

Email/username
or
Google
Facebook
Etc....

### Other details

Using backup sometimes some titles are missing in the library. So using account for safe keeping the titles in the library and no need to backup

**Comment by alessandrojean** [comment]
Not the app repository and not gonna happen as no one will pay for server costs as this is a open source project.
