### ISSUE TITLE
Document that 1 EPUB file = 1 chapter

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/website#1093]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

See https://github.com/tachiyomiorg/tachiyomi/issues/10208 for context.

**Comment by Pasqua101** [comment]
Hi there, is it possible for me to update the website to make note of this? If so, where you would like this change to be made.

**Comment by arkon** [comment]
Yes, of course. Probably somewhere in here: https://tachiyomi.org/docs/guides/local-source/
