### ISSUE TITLE
Language Select

### ISSUE THREAD

**Issue by arislee1998** [tachiyomiorg/website#110]
How about adding a Language Selector so that every users around the world can choose their familiar language? The translation can be based on Weblate.

**Comment by arkon** [comment]
There's too much content that's more subject to changing often. I'm not confident translations would be updated or complete enough for this to work.

**Comment by Soitora** [comment]
Adding translated menus and such is very easy, but there would be no point in it, as Arkon said, barely any content would be translated.

Maybe the main installation guide but other than that things change a lot, and quick.

**Comment by arislee1998** [comment]
Sure they are. All right.😉
