### ISSUE TITLE
Outdated extension

### ISSUE THREAD

**Issue by irzal221** [tachiyomiorg/website#1108]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1. I downloaded the manhwa on the extension bato.to | 2. I then read it as usual

### Expected behavior

The download went well before without any problems 

### Actual behavior

![Screenshot_2024-01-07-13-32-45-264_eu kanade tachiyomi-edit](https://github.com/tachiyomiorg/website/assets/155867189/3bad5561-e094-4e38-a924-26e6dfc99241)
Then when I wanted to use it today, I couldn't download manhwa as usual, something like that appeared.

### Other details

I checked that this extension is outdated, maybe it can be developed again, because I need it.
![Screenshot_2024-01-07-13-19-31-482_eu kanade tachiyomi](https://github.com/tachiyomiorg/website/assets/155867189/4d5c9bea-5092-47f0-a921-88ed417526f0)
![Screenshot_2024-01-07-13-17-31-590_eu kanade tachiyomi-edit](https://github.com/tachiyomiorg/website/assets/155867189/05459e0b-fa80-43cd-9671-989e7c17a156)

**Comment by alessandrojean** [comment]
This isn't the extension repository and as this extension is obsolete we don't offer any support to it.

**Comment by irzal221** [comment]
> This isn't the extensions repository and as this extension is obsolete we don't offer any support to it.

Please provide support for this extension, I really need it😔
