### ISSUE TITLE
Search -> Filter -> *Finished Reading, *Reading, *Unread

### ISSUE THREAD

**Issue by kanesheenpr** [tachiyomiorg/website#1111]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

When searching, It should have a "filter" on all the extensions that indicate the "finished reading", "unread" and "reading".

**Comment by alessandrojean** [comment]
This isn't the app repository.
