### ISSUE TITLE
Make FAQ (especially Extensions) more accessible

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/website#126]
Currently, as shown on Discord screenshot, the FAQ section on sidebar is very hard to reach, especially Extensions FAQ. One has to scroll past all Application FAQ entries to reach that, which is not user friendly. Thus I'm requesting the FAQ sections to be more accessible. Possibly linked on Home page like Manga Rock, but ultimately whichever works best.

**Comment by Soitora** [comment]
Fixed by #149
