### ISSUE TITLE
Add build check to pull requests

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/website#13]

**Comment by Soitora** [comment]
Did you successfully add this?

**Comment by arkon** [comment]
Yup, it failed for #18 : https://github.com/tachiyomiorg/website/commit/cda8a4fa378267312db5816eb783b721f11f391d/checks

**Comment by Soitora** [comment]
Good job, fixed with your commit: 7bb6560698f29855b40bf8261e201f5d068ef533.
