### ISSUE TITLE
Cant download or see chapter in mangakakalot extensions

### ISSUE THREAD

**Issue by MythVern** [tachiyomiorg/website#133]
Just like title above, it just certain of manga cant download. The manga i try to read and download is **Boukensha Ni Naritai To Miyako Ni Deteitta Musume Ga S Rank Ni Natteta**

![Screenshot_20200408-101714](https://user-images.githubusercontent.com/38820648/78737737-d7b69d00-7982-11ea-9414-abb5e85d6232.jpg)

**Comment by joseph619** [comment]
Wrong repo, this is for the Tachiyomi.org website, not the app.

**Comment by MythVern** [comment]
Sorry i am idiot to post it here
