### ISSUE TITLE
Add more guides (e.g. how to make Categories, Source Migration & Library Filters etc.)

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/website#14]
The website should have tips sections so that people can learn to use useful Tachiyomi features, like creating Categories, migrate sources and filters in My Library etc. I don't have preference for the image format, both still and GIF is fine by me.

**Comment by arkon** [comment]
The guides section should contain this, yes.

**Comment by joseph619** [comment]
This is also done
