### ISSUE TITLE
Long Tap Dialog issue

### ISSUE THREAD

**Issue by Zcheng1995** [tachiyomiorg/website#141]
I have the long tap dialog disabled, but if I were to manually skip to the next chapter, for some reason the long tap dialog would work again even though it is disabled.

**Comment by arkon** [comment]
Wrong repo, but I'll look into it.

**Comment by arkon** [comment]
Seems to be working as intended. Note that the long tap dialog is still supposed to work if the toolbars are shown.

**Comment by Zcheng1995** [comment]
I see, I did not know about the toolbar part, got it, thanks
