### ISSUE TITLE
Update front page sample image for Catalogues

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/website#15]
On Tachiyomi website, the front page sample image for Catalogues is outdated, as Batoto is dead and Mangafox is no longer supported. Thus, Batoto should be replaced by Mangadex and Mangafox should be replaced by Mangakakalot (as it's one of the top 3 recommended extensions).

![](https://tachiyomi.org/assets/media/screens.png)

**Comment by Soitora** [comment]
The real question is why are we using iPhone (or its copycat) design for the images with an Android app, I'll look into this, thank you.

**Comment by joseph619** [comment]
Thanks for taking care of this issue, maybe you could change the phone model to Pixel 3 (or Galaxy S10)?

**Comment by Soitora** [comment]
It was actually the Pixel 1 haha, damn that looks way too similiar to iPhone, will see if I can change to Pixel 2 or Pixel 3

**Comment by arkon** [comment]
Might as well wait for the Pixel 4. Or just use another phone, Pixels don't look that good anyway.

**Comment by Soitora** [comment]
Already completed the new based on the S9, will upload momentarily
