### ISSUE TITLE
Unnecessary header in Help Center

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/website#184]
The README didn't say that non-contributors couldn't open issues, but if that is the case, please point me to the proper directory.

Anyways, the big "Help Center" header at the top of the help center is unnecessary (as the page does not have multiple sections) and visually off-putting (given that it is right-justified while everything else is centered).

**Comment by Soitora** [comment]
Hey, of course you're welcome to open an issue here

I get your feedback and I will think it over as well as ask for others input.

I personally felt it was too empty without the header.

**Comment by specterflare** [comment]
I can see how you could feel that way; personally, I think it would look OK either way. If you want it to stay put, do you think centering it might be more appealing, visually speaking? Or do you want all headers to stay on the left?

**Comment by specterflare** [comment]
Here, I made some mock-ups
Currently:

![Screenshot (225)](https://user-images.githubusercontent.com/61708534/81619315-4c805b00-93b7-11ea-8baa-28e1993151a0.png)

Getting rid of the header:

![Screenshot (225)](https://user-images.githubusercontent.com/61708534/81619339-5e61fe00-93b7-11ea-8c33-3d91a6ef8283.jpg)

Centering the header:
![Screenshot (225) (1)](https://user-images.githubusercontent.com/61708534/81619361-67eb6600-93b7-11ea-9079-c330f0abbd89.jpg)

**Comment by Soitora** [comment]
Hey, great mockups

I'll check back on you tomorrow as it's really late now :)
