### ISSUE TITLE
Indicate which help center links lead outside the site

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/website#191]
I hope I'm not being a bother by opening these issues. If I am, feel free to let me know.

At the moment, there is inconsistent messaging about links outside the site. The Github link in the corner has an icon indicating it leads outside the site, but the Reddit, Discord, and Github squares in the help center do not. 

Current look:

![Screenshot (230)](https://user-images.githubusercontent.com/61708534/81720756-d4647480-944c-11ea-9a43-8b3baa98d5ab.png)

It would be more informative to add those icons.

Proposed change:

![Screenshot (230)](https://user-images.githubusercontent.com/61708534/81720804-e514ea80-944c-11ea-9502-b72014836648.jpg)

While I'm on the subject, was there a reason why the Links dropdown was removed from the top, and just the Github link was left?

**Comment by Soitora** [comment]
If there's anything that can be improved then of course I'm all ears

I'm unsure how I feel about adding external link symbol though

GitHub being kept is built-in (although can be removed), I personally felt it was important enough to stay featured

**Comment by specterflare** [comment]
If you don't want to add the symbol, have you considered removing those cards entirely and just re-implementing the Links dropdown? Or do you want the eight modules for symmetry?

**Comment by Soitora** [comment]
The eight modules for symmetry is definetly something I purposely made

If anything I might add a special on hover color for the icons to make them stand out more

**Comment by specterflare** [comment]
Ok, that makes sense. I'll close the issue then.
