### ISSUE TITLE
[Bug] Hamburger menu cannot be opened on mobile while in Help Center

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/website#198]
Basically just the title. The menu seems to work just fine on every other page, though.

**Comment by Soitora** [comment]
Yeah I've noticed that, it's pretty stupid actually.
So I've disabled Sidebar, which is intended, but apparently since Navbar is in the sidebar on mobile that gets disabled too... 👎

**Comment by specterflare** [comment]
That sucks. Is there any way around that? And why does it work on the other pages?

**Comment by Soitora** [comment]
> That sucks. Is there any way around that? Why does it work on the other pages?

Does it work inside a forks page? Like if you enter Neko?

**Comment by specterflare** [comment]
Yes. The only page it does not work on is the Help Center. Let me see if I can get you a video.

**Comment by specterflare** [comment]
Tada

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/61708534/81971059-7bccdd00-95ee-11ea-8403-5137238c8450.gif)

**Comment by Soitora** [comment]
Might just be me needing to import the files necessary then, I'll check it out when I can

**Comment by specterflare** [comment]
Thanks!
