### ISSUE TITLE
Forks page header is not centered

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/website#201]
Currently, both Home page and Help has the header centered, thus Forks page should also be centered for consistency.

**Comment by Soitora** [comment]
I don't completely agree that Extensions (or any other normal page) should have centered, it has sidebar and is much more similiar to FAQ and others. I tried it out locally and on some pages it looked really weird.

If anything, for consistency, the Forks pages should have centered H1

**Comment by joseph619** [comment]
I guess Forks is fine then, I will change it to Forks only.

**Comment by arkon** [comment]
I also disagree, there's plenty of pages that don't have centred headers.
