### ISSUE TITLE
Side navigation get overlay onto content

### ISSUE THREAD

**Issue by GHOSTBEAR** [tachiyomiorg/website#202]
This occurs on more narrow screens
And is prominent on FAQ, Guides, Fork, Contribution, and Extensions

Images of issue:
![image](https://user-images.githubusercontent.com/6576096/82119247-207d2500-977d-11ea-9234-60f5ea2c8861.png)

![image](https://user-images.githubusercontent.com/6576096/82119215-fcb9df00-977c-11ea-8d80-51f951ca88d2.png)

**Comment by Soitora** [comment]
Might be due to the padding override I did for Help.vue (if that was the one).
