### ISSUE TITLE
problem when a lot of manga of same name get collected at different tabs

### ISSUE THREAD

**Issue by suvendu1997** [tachiyomiorg/website#205]
This problem occurs when we add manga of the same name from different websites. This creates the same manga to be added to tachiyomi. Hence we have to search various tabs to search which manga from which sites has gotten updated.
Try to solve this problem. I am thinking to add a folder system inside the tab, so to add all manga of the same name into the same folder.
 And solves the problem of searching in all the tabs.

**Comment by AbdullahM0hamed** [comment]
If I understood you correctly, this shouldn't be in this repo.
