### ISSUE TITLE
FAQ: Better Description for Stable and Preview 

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/website#206]
At the moment, there's no description in the site that shows the disntinction between Stable and Preview. Many users download Preview and expect it to run smoothly as their daily driver. 

Preview description should state something like it's a beta testing version of Stable which has more new features but also potential bugs (also mention to turn on Auto backup if something in Preview breaks the app) etc.

**Comment by Soitora** [comment]
Aside from the Getting started page, Preview is pretty much already described as there's a warning to accept before user is allowed to download.

Also, stable is no longer named (except, again, in Getting started)

**Comment by joseph619** [comment]
I was thinking of adding a description on Guides as well, more elaborate to point out differences (such as weekly updates instead of indefinite ones)

As for the naming...what's the plan for that? Do we plan to drop Stable entirely?

**Comment by Soitora** [comment]
It shouldn't be added as a guide, at most maybe a FAQ entry.

Releases is technically still "Stable X.Y.Z" and Dev is "Preview r0000".

I'd prefer not to name it Stable, just Tachiyomi and Tachiyomi Preview.

**Comment by joseph619** [comment]
Understood, maybe it could be under App section

What is Preview?

Then a description for it.

**Comment by Soitora** [comment]
Yes, app section if any.

Maybe a better title, but kind of like that description
