### ISSUE TITLE
Chapters locked on Tapas extension 

### ISSUE THREAD

**Issue by LunaEden** [tachiyomiorg/website#207]
The chapters on tapas are showing up as locked and are unreadable, it shows a message saying to login and refresh but even after doing that the chapters remain locked. I asked about this on the Discord channel but I decided to address the issue here so it could be fixed sooner. This is my first time using github to report an issue so I'm sorry if I'm doing this wrong 😬 Please look into this issue, thank you :)

**Comment by joseph619** [comment]
Wrong repo

**Comment by LunaEden** [comment]
Oh no! Sorry!😔 Where can I report the issue then?

**Comment by arkon** [comment]
https://github.com/inorichi/tachiyomi-extensions
