### ISSUE TITLE
FAQ: Add "Always show chapter transition" option description

### ISSUE THREAD

**Issue by scb261** [tachiyomiorg/website#216]
I have [manga](https://mangakakalot.com/read-qu4wd158504821675), where each chapter has one page (not exactly, but the app sees it as separate chapters). So I tried to set this option off, but it almost always show chapter transition (from the option name I guess it's the right behavior). It would be good to have description on [the reader setting page](https://tachiyomi.org/help/guides/reader-settings/) with explanation when it show the transition and when it doesn't. And maybe some way to reduce number of situations when it does.

**Comment by scb261** [comment]
Related to bug inorichi/tachiyomi#3079. Since it probably will be fixed, no need to add explanations about single paged chapters (or maybe add it now and remove it when fixed).

Workaraund for now:
1. Skip current single-paged chapter and go to the transition between the current and the next.
2. Return to the current chapter and read it while the next one is loading (even if it's already downloaded, it's still needed to be loaded from storage).
3. Now the next chapter is current, go to step 1.

The option description still should be added with explanation that when it turned off, the transition still will be showed if the next chapter isn't ready (for example slow internet or it's even doesn't try because of the bug, that I mentioned above).

**Comment by Soitora** [comment]
Thank you for the input, we'll check if we need to add to the website a FAQ entry about it or if making it clearer in the app is a better choice (probably is)
