### ISSUE TITLE
Top level `/help` entry point

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/website#25]
`https://tachiyomi.org/help/` should have some simple pointers to different parts of the help section (e.g. guides, FAQ, etc.).

This will act as the entry point from various places, including the "Help" entry in the app's side nav.

Examples:
- https://nabstudio.zendesk.com/hc/en-us
- https://support.discordapp.com/hc/en-us

**Comment by Soitora** [comment]
#31 should be a small bit of this, but it would be nice to have an even better page for it.
