### ISSUE TITLE
Inconsistency in Forks page

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/website#261]
Every other page in the Help Center (FAQ, Guide, etc.) is under the /help/ parent in the URL, so for example /help/faq/ or /help/guides/. But Forks is separate, just tachiyomi.org/forks. I assume this is an error. How would one fix this; just go through the files and change every reference of /forks/ to /help/forks?

**Comment by Soitora** [comment]
You assume this is an error but it's not, it's completely intentional. This is also why they don't have a sidebar, to give them their own page to represent their fork on and not just be a sub help page
