### ISSUE TITLE
Better incorporate Downloads page

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/website#267]
I think it would make more sense if the Download button on the home page redirected to the downloads page, instead of splitting up downloads into two locations. I'd make a PR myself if I knew how to do this lol.

**Comment by Soitora** [comment]
Might be looked on in the future, was planning on making that page a little better but no idea how to go about it

**Comment by specterflare** [comment]
If you're open to suggestions, here is a mock-up of how I would do it:

![Screenshot (59) (1) (1)](https://user-images.githubusercontent.com/61708534/88503625-48201300-cfa0-11ea-9a95-c9706a8b9f58.png)

Step one is obviously to add in the sidebar since it makes no sense to have the downloads page on it but not show it on the actual page. Also, you know, consistency.

I would also rename "Release notes" to "Changelog" and center it. Additionally, I would merge the latest release line into the description, and mention when Preview drops. Now that I think about it, it would probably be good to explicitly mention you need Andriod 5.0 or above in that paragraph as well.

Obviously I couldn't include it in the mockup, but I would lastly add the Preview warning you get from the Download button on the homepage to the one hear. Finally, redirect the download button on the homepage to hear, and viola!

**Comment by specterflare** [comment]
Plz notice me

**Comment by specterflare** [comment]
Hello?

**Comment by AbdullahM0hamed** [comment]
The void returns your greeting.

Just kidding, greetings are an illusion and so is the void. 

And so is being noticed.

**Comment by specterflare** [comment]
Alas

**Comment by Soitora** [comment]
I'm looking in to this already.

**Some things will probably not be done:**
1. Will most likely not add the sidebar, it's an independent page.
1. Will not add preview release schedule (yet), as it's not static and moves slightly every release.

**Some things I've been looking at:**
1. Adding a relative time showing last time something was updated
![image](https://user-images.githubusercontent.com/10836780/88729668-b7c70700-d134-11ea-8c95-55af75cefd06.png)
1. **Alternatively**: When/if @arkon switches Preview builds from Travis to GitHub Actions add the preview schedule with local timezone presented to user.
1. Updating the design of the download buttons
1. Proper display of the Android version requirement
1. Adding an indicator of the current Preview build version, but last time I tried to parse Kanade website it forbade the cross-origin request.

I'm not ignoring your issue, just don't needlessly bump it like you did above please
