### ISSUE TITLE
Enhance Local Manga Guide's Folder Structure 

### ISSUE THREAD

**Issue by happywillow0** [tachiyomiorg/website#29]
Would it make any more sense to utilize a folder structure tree on the Reading local manga guide page? This may look better and be more self explanatory:

```
/Tachiyomi
   /local
      /My Manga 1
         /Ch 1
            images
         /Ch 2
            images
      /My Manga 2...
```
Or something of that nature.
[Idea from Plex Help](https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/)

**Comment by alessandrojean** [comment]
Will work on this now.
