### ISSUE TITLE
FAQ: Add Inorichi statement about adding to Google Play store

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/website#307]
https://github.com/inorichi/tachiyomi/issues/1745#issuecomment-441208074

**Comment by joseph619** [comment]
Quoting him directyl

> Sorry but I'm not going to deal with google play policies, nor dropping the apk system (in fact before the apk extensions arrived, I was using extensions with YAML files and they were very limited, so I won't invest any more time there.
> 
> I'm sure it would be taken down sooner or later, and I'm not going to risk a developer account for a fun/hobby project with no profit at all.
