### ISSUE TITLE
Guides: Remove inbuilt extension mentions aside from exhentai

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/website#312]

**Comment by Seishirou101** [comment]
Not able to completely remove inbuilt extensions because AZ and EH still has them, so will make it more clear.

**Comment by joseph619** [comment]
We don't mention EH on the site anymore, as the fork is no longer maintained

**Comment by Seishirou101** [comment]
@loocool2 mentioned that we should keep it cause EH still has them and people can still make backups from it. We also technically still have the page for EH still up too
