### ISSUE TITLE
FAQ: Add known dead sources

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/website#319]
MangaRock: Dead.
MangaGo: A pain to scrape manga from. 
MangaCards: DMCA
Boredom Society: DMCA
KissManga: DMCA
MangaKisa: Shutdown
MangaBoom: All sources dead
MangaFox: No one wanted to deal with it

**Comment by Seishirou101** [comment]
possibly include in the extensions section.

**Comment by joseph619** [comment]
Rather than dead sources, could just mention sources that won't be added again (like Japscan). People forget about dead sources quickly and won't care soon.

**Comment by yostinJB1** [comment]
Podrían agregar manga.in

**Comment by Soitora** [comment]
> Podrían agregar manga.in

Roughly translated, I think this means to add status for manga.in as it's dead too?
