### ISSUE TITLE
my download got stuck

### ISSUE THREAD

**Issue by thepanchalshadow** [tachiyomiorg/website#369]
The download got stuck for only 1 last page and it's not just one but it happend with two manga constantly. And doesn't even show the error like time out or something but no there's not any kind of error still the download is stuck at the last page the mangas are
1.[Sena Youtarou] Natsu-jiru ~Ase ni Mamirete Gucchagucha~ Ch. 2-10 [English] [SaHa + Team Koinaka] extension used NineHentai(EN)
2.[Toyo] Asoko Araiya no Oshigoto | Traditional Job of Washing Girls' Body Ch. 1-91 [English] [Ongoing] extension used NineHentai (EN)
![Screenshot_20200929-193028_Tachiyomi](https://user-images.githubusercontent.com/71685795/94570450-646d5400-025e-11eb-8d06-107141bed00a.jpg)
![Uploading Screenshot_20200929-193028_Tachiyomi.jpg…]()

**Comment by Soitora** [comment]
Wrong repo, check [inorichi/tachiyomi](https://github.com/inorichi/tachiyomi/issues) if anyone else has this issue.
