### ISSUE TITLE
Configure domain

### ISSUE THREAD

**Issue by arkon** [tachiyomiorg/website#4]
We can keep hosting it via GitHub Pages, but a proper domain would be nice. Can also rename the repo to something like `website` or `pages` afterwards.

**Comment by Soitora** [comment]
Yeah, buying the domain `tachiyomi.org` could maybe be something? Is fairly cheap

**Comment by arkon** [comment]
`https://tachiyomi.org` is being configured with GitHub/Cloudflare. Should be up at some point.

**Comment by arkon** [comment]
Test
