### ISSUE TITLE
Parser for latest GitHub release

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/website#43]
I'd like someone to make a parser in a way that allows us to have a button that downloads the latest `.apk` from GitHub. Using the `/release` URL isn't possible as it only allows direct-download if you specify the filename, but since we use the version in the APK filename that is a no-go.

The wanted tags is `tag_name` and `browser_download_url` from <https://api.github.com/repos/inorichi/tachiyomi/releases/latest>.

If you can, make a makeshift button for the front-page like the **Get Started** button that downloads APK directly.

**Comment by alessandrojean** [comment]
I can help with that. Since it will require creating a custom layout, it will make #44 easier later.

**Comment by arkon** [comment]
You pretty much just need to make a request for that URL, parse the JSON (e.g. with `JSON#parse`), then grab the fields from the resulting JS object.

**Comment by alessandrojean** [comment]
That's what I am doing :)
