### ISSUE TITLE
FAQ: Add sources that aren't going to added back

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/website#461]
mangaworld, mangadisk, asura scans, mangastine, mangago,mangafox

**Comment by scb261** [comment]
https://github.com/inorichi/tachiyomi-extensions/issues/3475 for more sources

**Comment by Kiki88x** [comment]
Please add hyperdex.Com for the extension. I dont know how to do it.

**Comment by CrepeTF** [comment]
@Kiki88x I think you're in the wrong repo buddy
