### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by zDrie** [tachiyomiorg/website#490]
Hi! I wanna siggest a new Feature. Categories are used to organize our readings, sometimes we need to separate somethings which already have common characteristics
![Screenshot_20210103-184803_WhatsApp](https://user-images.githubusercontent.com/54642241/103489628-a5907980-4df4-11eb-860b-07bb8cf55cd2.jpg)
'A' haves my current categories
'B' haves a modification on 'unread' (No leidos) 
On 'unreads' i put mangas / manwhas / light novels that i wish to read in the future. Also, when i want to look for something to read i search here. But i dont want to open and close a lot of mangas when i want to read a light novel for example... for that it was convenient to create subcategories.

- but Drie, you can create a new category to do that
- well Karen, if i create a new category for which one i need the searching will be very unefficient (i i have to scrolling a lot)

**Comment by scb261** [comment]
1. Wrong repository ~~how do you end up in this repo :harold:~~
2. You can add your vision of this to https://github.com/tachiyomiorg/tachiyomi/issues/1803

**Comment by zDrie** [comment]
Oh i just clicked on a link puted on the tachiyomi's Discord, sorryEl 3 ene. 2021 19:56, scb261 <notifications@github.com> escribió:
Wrong repository how do you end up in this repo :harold:You can add your vision of this to tachiyomiorg/tachiyomi#1803
