### ISSUE TITLE
Guides: Add Viewer Navigation to Reader Settings

### ISSUE THREAD

**Issue by ghostbear** [tachiyomiorg/website#503]
The app doesn't show how any of the navigations work for Viewer Navigation. 

What to add:
- Heading
- Short description
- An carousel containing images showing each navigation type with colors to visualize the tapping areas (manga page as background)

Invert tapping sections will have to be reworded

---

**Notes on how each works**:

**Defaults**: Works as it did before for all reading modes

**Pager Default**: 
```
Visualization of default state without any inversion
+---+---+---+
| L | M | R |   R: Move Right
+---+---+---+
| L | M | R |   M: Menu
+---+---+---+
| L | M | R |   L: Move Left
+---+---+---+
```

**Webtoon Default**: Has the same tapping regions as L navigation

**Edge**:
```
Visualization of default state without any inversion
+---+---+---+
| N | M | N |   P: Previous
+---+---+---+
| N | M | N |   M: Menu
+---+---+---+
| N | P | N |   N: Next
+---+---+---+
```
**Kindlish**:
```
Visualization of default state without any inversion
+---+---+---+
| M | M | M |   P: Previous
+---+---+---+
| P | N | N |   M: Menu
+---+---+---+
| P | N | N |   N: Next
+---+---+---+
```
**L**:
```
Visualization of default state without any inversion
+---+---+---+
| P | P | P |   P: Previous
+---+---+---+
| P | M | N |   M: Menu
+---+---+---+
| N | N | N |   N: Next
+---+---+---+
```

---

EDIT: Explain the carousel part a bit clearer

**Comment by Soitora** [comment]
Maybe have pictures of a manga (like the one on the frontpage) and overlay colors to visualize?

**Comment by scb261** [comment]
I looked into it a little bit and it's kinda odd to have two identical navigations in webtoon mode (default and L) while preventing ||| shaped navigation that available in pager. Not the right place to discuss it, but maybe at least hold it until it comes to stable

As for overlay for whoever will do it:
```
+---+---+---+
|   |   |   | 0.25
+---+---+---+
|   |   |   | 0.75
+---+---+---+
|   |   |   | 0.25
+---+---+---+
|1/3|1/3|1/3|
```

**Comment by ghostbear** [comment]
> I looked into it a little bit and it's kinda odd to have two identical navigations in webtoon mode (default and L) while preventing ||| shaped navigation that available in pager. Not the right place to discuss it, but maybe at least hold it until it comes to stable

Default (Webtoon ) and L Navigation could be together in the carousel.

For Default (Pager), it would probably use different colors to indicate that it moves right and left instead of next and previous

Yes it would probably not get merged until the next stable release

If anyone asks how the different navigation types work until then link them here https://github.com/tachiyomiorg/website/issues/503#issue-785346504, the notes should somewhat explain how they work

**Comment by ghostbear** [comment]
I made some images to visualize each navigation mode. If someone has any feedback it would be appreciated 

| Pager | L |
|---|---|
| ![pager_default](https://user-images.githubusercontent.com/6576096/107127173-99e11880-68b4-11eb-9d8b-36d1b7f52f31.png) | ![l](https://user-images.githubusercontent.com/6576096/107127178-9f3e6300-68b4-11eb-9745-42c773c4457d.png) |
| This uses RIGHT and LEFT to navigate which none of the other have. This could use other colors to visualize that ||

| Kindlish | Edge |
|---|---|
| ![kindlish](https://user-images.githubusercontent.com/6576096/107127185-b1b89c80-68b4-11eb-8258-56cb344e7dea.png) | ![edge](https://user-images.githubusercontent.com/6576096/107127190-b67d5080-68b4-11eb-9e71-3a753e9b433d.png) |

Krita Project File: [navigation_kirta.zip](https://github.com/tachiyomiorg/website/files/5937443/navigation_kirta.zip)

**Comment by arkon** [comment]
I assume the plan is to have a legend for the colours? At first glance it's hard to understand what they mean.

**Comment by scb261** [comment]
I think ideally there would be 4 layouts * 4 invert modes = 16 images, since it isn't clear how inverting modes affect different layouts. And now that I think about it, reading mode also affect this (RTL vs LTR). So it's 32 images? Seems a bit too much tbh, not sure now if it's actually needed

**Comment by ghostbear** [comment]
> I assume the plan is to have a legend for the colours? At first glance it's hard to understand what they mean.

Yes a legend will be added, either integrated into the image or below as plain text

> I think ideally there would be 4 layouts * 4 invert modes = 16 images, since it isn't clear how inverting modes affect different layouts. And now that I think about it, reading mode also affect this (RTL vs LTR). So it's 32 images? Seems a bit too much tbh, not sure now if it's actually needed

I think just having the images just display the default state would be better and not have an overflow of images. Then leave the inversions for the users imagination. But I see that not all users would understand how the inversion modes are applied. And for RTL and LTR there is only one navigation mode affected by it Pager (or Right to Left), and maybe different color would be better for it to illustrate that it different from the others

> Maybe some way to generate overlay on client side based on what they ticked?

This could probably be added to the app by using the Rect instances from the navigation class, but that could be very complex to add. Similar thing could be added to the website but that would also be complex

**Comment by Soitora** [comment]
Representing the French flag smh 🦀

**Comment by ghostbear** [comment]
**curche** on Discord made some images to visualize the reading modes. Now the question is which one to use a legend or pills with text. I would say either the pills with Tachi color or the legend 

| Moon+ variant | Moon+ variant with Tachi colors | With legend |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/6576096/107142659-bfac0300-6930-11eb-8a51-b98bcf655248.png) | ![Edge_Nav_Light2](https://user-images.githubusercontent.com/6576096/107142756-5e386400-6931-11eb-8f43-e8b1c5bb2feb.png) | ![image](https://user-images.githubusercontent.com/6576096/107142663-c2a6f380-6930-11eb-8e3f-642f3d8c1992.png) |

**Comment by curche** [comment]
Link to view the Figma Project
https://www.figma.com/file/PxHyXAuDebeTSj5IYaRcFR/tachi-reader-nav?node-id=0%3A1

Exported PNGs
[ReaderNavGuideImages.zip](https://github.com/tachiyomiorg/website/files/5950995/ReaderNavGuideImages.zip)
