### ISSUE TITLE
Pages are always "Last updated: a minute ago"

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/website#563]
No matter what, every page on the site says "Last updated: a minute ago". I'm not sure when it broke, but I do have distinct memories of it not being broken.

**Comment by specterflare** [comment]
Anyone?

**Comment by ghostbear** [comment]
The package handling "Last updated:" is probably broken `@mr-hope/vuepress-plugin-last-update`. And I can't find the documentation for it, so I have a suspicion that it has turned into `@mr-hope/vuepress-plugin-git`.

**Comment by arkon** [comment]
Someone could try checking out old commits to see when it broke, but I agree with @ghostbear that it probably broke on an update to that plugin dep.

**Comment by ghostbear** [comment]
Just noticed that the PR #565, #567 and #568 seem to display the correct time for "Last updated"
![Screenshot from 2021-03-09 19-18-53](https://user-images.githubusercontent.com/6576096/110518377-50325a80-810c-11eb-85d2-e6b53e7980c2.png)

**Comment by scb261** [comment]
Maybe it should use `@vuepress/plugin-last-updated`? Idk how to test it, since both local and netlify show it correctly even with current config

**Comment by Soitora** [comment]
We changed from that one to Mr-Hope because Vuepress didnt offer any flexibility. I believe the new one from Mr-Hope is the `@mr-hope/vuepress-plugin-git` as ghostbear mentioned.

**Comment by ghostbear** [comment]
Looks like #587 didn't fix the problem. Starting to think that it has something to do with the build script because it works fine locally

**Comment by Soitora** [comment]
>  Starting to think that it has something to do with the build script because it works fine locally
Also works fine on Netlify

**Comment by ghostbear** [comment]
Hmm, it's probably `actions/checkout@v2` because it only gets the latest commit.
And by doing a shallow clone `--depth 1` I'm able to recreate the issue, so it may be `actions/checkout@v2` that changed at some point

**Comment by Soitora** [comment]
As I mentioned on #website, we could switch the site to Netlify and get an open-source team (https://www.netlify.com/legal/open-source-policy)

We'd need a Code of Conduct for that though, so looking into some simple ones

**Comment by Flat** [comment]
> 
> 
> As I mentioned on discord#website, we could switch the site to Netlify and get an open-source team (https://www.netlify.com/legal/open-source-policy)
> 
> We'd need a Code of Conduct for that though, so looking into some simple ones

https://github.com/karlgroves/dontbeadick

**Comment by yegorgunko** [comment]
I can confirm it, but for me it displays "a few seconds ago".
I doubt it is related to browser, but I represented it on latest Chrome on Android 11.

I can add that on my Vuepress website which is hosted on [Vercel](https://vercel.com/) and uses default [@vuepress/last-updated](https://vuepress.vuejs.org/plugin/official/plugin-last-updated.html) plugin it works as expected on local and on hosting. Here is a [config line](https://github.com/yegorgunko/es-doc/blob/d37e89fc64fc8a8ebb888cfefa793d44e06016f2/src/.vuepress/config.js#L63).

**Comment by yegorgunko** [comment]
Recently saw [this](https://blog.ksoichiro.com/post/2021/02/show-valid-last-updated/#confirm-actionscheckout) blog post and I believe it describes the exact same issue.

To summarize what I learned from it:
you can try changing your Workflow (`push.yml`) by adding:
```yml
steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0
```

**Comment by arkon** [comment]
That seemed to have fixed it (https://github.com/tachiyomiorg/website/commit/327ec78c4142f700b3b375a6149d37cada69700e).

Thanks @yegorgunko !
