### ISSUE TITLE
Download forbidden

### ISSUE THREAD

**Issue by msbakedpotatoes** [tachiyomiorg/website#566]
I have downloaded tachiyomi multiple times previous with no issues but today it's been saying that the download is forbidden

**Comment by ghostbear** [comment]
Is this after you select a version `Stable` or `Preview` this issue happens?

**Comment by msbakedpotatoes** [comment]
Yes I chose stable

**Comment by kotomonokeo** [comment]
What happen when you click download?

**Comment by msbakedpotatoes** [comment]
The file does get download but then it says download forbidden

**Comment by arkon** [comment]
Do you have a screenshot? Have you tried different browsers or networks?

**Comment by msbakedpotatoes** [comment]
I don't have a screenshot sorry. Yes I did and it didn't work

**Comment by kotomonokeo** [comment]
Did you try to download in mobile?
I try in mobile and got this after click download

![Screenshot_2021-08-01-15-46-34-69](https://user-images.githubusercontent.com/56149696/127765148-fe5f15a0-9a40-43fb-9b6f-fb038c2d8d8b.jpg)

If you try to download to in mobile and you got github installed you will got pop up to redirect to github or other browser. Download wont start before you choose.

Some browser will rediret to github the first time you try.

**Comment by arkon** [comment]
Closing since not enough info.
