### ISSUE TITLE
Proposed fixes

### ISSUE THREAD

**Issue by bbtora** [tachiyomiorg/website#6]
Working on the following improvements:
- Remove "Downloading and installing" heading
Sounds a bit odd just after "Installation".
-  Change app link from fixed 0.8.4 to latest release
-  "Browsing" to "Searching" in all instances in mangadex question
-  Remove "Mangadex: No results when browsing even after login." section
[This was fixed.](https://github.com/inorichi/tachiyomi-extensions/pull/1363)

Let me know if anything else can be improved and we can add that too.

**Comment by Soitora** [comment]
If the app was more consistent the Browse would be all Search, it's okay to switch though.
Regarding the rest I'm on board as well.

Do you wish to create a PR or just simply want me to change it?

**Comment by bbtora** [comment]
Yes, I'm ready with all the fixes. Will create a PR if nothing else is needed.
