### ISSUE TITLE
Update reader, add image and description for new buttons

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/website#605]
As the reader UI has been changed and new buttons were added, the reader images should be replaced and should have supporting images for each of the new button, explaining what they do.

**Comment by Seishirou101** [comment]
closing due to 
![1583-221-max](https://user-images.githubusercontent.com/57241064/122649217-65138680-d11c-11eb-9a8f-5c1951a761f1.png)
can be reopened if actually needed later
