### ISSUE TITLE
Date of Last Update is not Showing 

### ISSUE THREAD

**Issue by xyzzin** [tachiyomiorg/website#608]
Is this a bug or what? I can't see the date of update below the chapter of the manga i add on my library. How am I supposed to know when was the latest chapters was updated recently or years ago now. 
 
![Screenshot_20210417_031635](https://user-images.githubusercontent.com/82677303/115074290-171bb000-9f2c-11eb-8a71-148ddb294317.jpg)

**Comment by ghostbear** [comment]
Wrong repository. It's probably an issue with the extension you're using. Go report it in [tachiyomiorg/tachiyomi-extensions](https://github.com/tachiyomiorg/tachiyomi-extensions), and state what extension you're using
