### ISSUE TITLE
Please bring back the spreadsheet section of the extensions page

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/website#623]
I don't know when this change was made, but I just noticed a few minutes ago that the "Spreadsheet" tab on the extensions subpage has been replaced with what is, in my opinion, a severe downgrade. You can't search, can't sort, can't easily click on and open the source, and can't see the (often very helpful) notes. I humbly request that you bring back the old layout.

**Comment by Seishirou101** [comment]
The spreadsheet was manually maintained by a volunteer and it usually only included the extensions that share the same code. With the switch to splitting the extensions, this is no longer needed now as everything is split out into their own so users can find the extension they need. The maintainer of the spreadsheet isn't even adding to it anymore so it is currently unmaintained and out of date.

**Comment by arkon** [comment]
At best we could add sorting functionality. Searching is a native browser feature so that's redundant.

**Comment by ghostbear** [comment]
Closing this in favor of #624
