### ISSUE TITLE
Add more functionality to extension list

### ISSUE THREAD

**Issue by ghostbear** [tachiyomiorg/website#624]
- [ ] Search (Optional)
- [ ] Sort
- [ ] Filter by lang

**Comment by yegorgunko** [comment]
Can you please use checkboxes to visualize the progress, so contributors can see what needs to be done?

As I see, search feature isn't needed according to https://github.com/tachiyomiorg/website/issues/623#issuecomment-831304519

**Comment by yegorgunko** [comment]
Shouldn't it be closed by #636?
