### ISSUE TITLE
Manhuascans

### ISSUE THREAD

**Issue by akmalmeaw** [tachiyomiorg/website#653]
Why does manhuascans not working,??? When i tap the chapter, it says no pages found

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues

**Comment by rururubie** [comment]
It's still not working. I think the main site is the problem.

**Comment by rururubie** [comment]
Ohhh the webview is still working but on the tachiapps, it's not working
