### ISSUE TITLE
issue on one of the extensions

### ISSUE THREAD

**Issue by Alexishoe** [tachiyomiorg/website#654]
there's an issue on one of the best esxtansions on the app called "manhuascan" I'd love to if you fixed it quickly because it's only esxtansion i use. sorry for taking your time :(

**Comment by Alexishoe** [comment]
it updates normally and everything but when i click chapter is kicks me out and says "chapter not available" :(

**Comment by curche** [comment]
already reported https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7011
wait patiently for a fix or migrate to another source

you're also on the wrong place. Next time, report at https://github.com/tachiyomiorg/tachiyomi-extensions/
