### ISSUE TITLE
esxtansion doesn't work again :(

### ISSUE THREAD

**Issue by Alexishoe** [tachiyomiorg/website#657]
hi I'm sorry for taking your time again but manhuascan stopped working again 😭😭😭 it was fixed for like 12 hours yesterday and now i checked it and it still doesn't work 😭

**Comment by ghostbear** [comment]
Wrong repo [tachiyomiorg/tachiyomi-extensions](https://github.com/tachiyomiorg/tachiyomi-extensions)

Also known issue https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7054
