### ISSUE TITLE
Help Center header has no hamburger menu, and overlapping items in header on small screens

### ISSUE THREAD

**Issue by datreesezcup** [tachiyomiorg/website#715]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

- Go to https://tachiyomi.org/help/ on either:
   - A small screen mobile device (like a phone)
   - Desktop, and use the browsers devtools to shrink the size of the website thin

### Expected behavior

The page has a hamburger menu like all of the other pages, where the other navigation links reside, and there is no overlapping of anything

### Actual behavior

No hamburger menu present, and the top navigation links can overlap the Tachiyomi logo.

### Other details

Example of overlapping: 
![website_issue](https://user-images.githubusercontent.com/25621728/127358692-78018958-6137-4bc4-b504-133e645e8e8c.png)

**Comment by Soitora** [comment]
V2 wen

**Comment by dikasetyaprayogi** [comment]
+1 me too, phone res 1280x720

**Comment by AnujSsStw** [comment]
@yegorgunko yaa i was having a hard time to nav through it

**Comment by YeiserDeveloper** [comment]
### mobile
![image](https://github.com/tachiyomiorg/website/assets/97372908/9cb53209-d353-46d1-909b-e4986fcb3c30)

### desktop
![Captura desde 2023-07-10 20-48-32](https://github.com/tachiyomiorg/website/assets/97372908/8e2fb743-9d5a-4049-8e37-564b089b59fc)

I have this so far, but the button to open the menu doesn't have any functionality, and I don't know where to find it.
