### ISSUE TITLE
MANGAOWL: Failed to bypass clouflare

### ISSUE THREAD

**Issue by akmalmeaw** [tachiyomiorg/website#725]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1. Try to open through webview
2. Open with tachiyomi

### Expected behavior

1. Can open with tachiyomi
2. Can read all chapters
3. Can download chapters

### Actual behavior

1. Can read only through webview
2. Failed to bypass cloudflare
3. Can't open with tachiyomi

### Other details

![Screenshot_20210811-113249_Tachiyomi](https://user-images.githubusercontent.com/64727356/128966611-469ba8c7-31db-42de-915d-cf9a3469c236.jpg)
![Screenshot_20210811-113209_Tachiyomi](https://user-images.githubusercontent.com/64727356/128967254-12835526-3bfc-469c-b842-40f120bb2347.jpg)

**Comment by akmalmeaw** [comment]
Not much to say. It was updated today but i hope this source can be saved because i dont know any extension better than mangaowl after manhuascan taken off. Tq

**Comment by Seishirou101** [comment]
you're in the wrong repo, but cloudflare is just like that. If you already did the troubleshooting then thats all you can do. migrate to something that has less cloudflare security.
