### ISSUE TITLE
Add extension

### ISSUE THREAD

**Issue by kinglessy** [tachiyomiorg/website#782]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Hello, been using the app for a long time and really hope you add a website as an extension it's mangafox
 http://m.fanfox.net/ 

### Other details

It was once http://mangafox.me/ but turns automatically to http://m.fanfox.net/

**Comment by Seishirou101** [comment]
you're in the wrong repo.
