### ISSUE TITLE
app problem after backup

### ISSUE THREAD

**Issue by jotasuke** [tachiyomiorg/website#820]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

when I enter the application it exits and stops working 

### Expected behavior

after the backup I thought it would work normally 

### Actual behavior

and instead it stops working

**Comment by Seishirou101** [comment]
not the right repo, and not enough information, you can go into discord and get help in #support

**Comment by jotasuke** [comment]
I backup the tachiyomi and restored it but the app is now stopping it keeps
coming out

Em dom, 2 de jan de 2022 17:01, Seishirou101 ***@***.***>
escreveu:

**Comment by alessandrojean** [comment]
> Assumindo pelo "*escreveu*" na sua mensagem que você fala Português. 

Você está preenchendo a Issue no lugar errado.

Peça por ajuda no canal #support no [Discord do Tachiyomi](https://discord.gg/tachiyomi).
