### ISSUE TITLE
Show latest chapter number in overview in migration window

### ISSUE THREAD

**Issue by MikanOrangePawaaa** [tachiyomiorg/website#847]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I'm migrating some Manga rn, but a lot of the sources have different chapters as their latest release, and it is a pain to look for the one that has the most current release.  You have to long-press each source and check manually right now. A little number indicator as it is shown in ibrary already would be useful (Potentially also in the browse window)

**Comment by Seishirou101** [comment]
wrong repo, but its already been requested. [#2867](https://github.com/tachiyomiorg/tachiyomi/issues/2867)
