### ISSUE TITLE
Aderir nueva extension

### ISSUE THREAD

**Issue by Acsell7u7** [tachiyomiorg/website#856]
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

La pagina se llama "AHSTUDIOS" y como es de esperarse una extension así no puede quedar de lado, le iría muy bien a Tachiyomi.

### Other details

Así como yo son muchos a los que les encanta esta pagina.

**Comment by Seishirou101** [comment]
wrong repo.
