### ISSUE TITLE
Manga

### ISSUE THREAD

**Issue by Tadaningenda** [tachiyomiorg/website#863]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

I can't find it

### Expected behavior

When i search for manga slayer app i can't find it

### Actual behavior

It's ana app but it should be in tachiyomi too

**Comment by curche** [comment]
1. You're at the wrong place. 
2. If you want to request for a site/source to be added to the app, then request at Tachiyomi Extensions GitHub or by clicking [here](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose)
