### ISSUE TITLE
Doujindesu NXDOMAIN

### ISSUE THREAD

**Issue by CanULetMeIn** [tachiyomiorg/website#871]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

open browse
open doujindesu
issue here, can't open because 212.32.226.234: NXDOMAIN

### Expected behavior

this should can open and read

### Actual behavior

this happened can't open and read

**Comment by arkon** [comment]
Wrong repo.
