### ISSUE TITLE
The application does not open

### ISSUE THREAD

**Issue by itariago** [tachiyomiorg/website#874]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

I click on the app, however, it simply closes and says that the app gave an error and asks to open it again, I've tried that too, but it doesn't work

### Expected behavior

start normally

### Actual behavior

not simply open

**Comment by arkon** [comment]
Wrong repo.

**Comment by itariago** [comment]
> Wrong repo.
sorry i don't speak english i used the translator to try to solve the problem i'm having so i didn't understand much
