### ISSUE TITLE
possible addition to the "only search pinned extensions"global search

### ISSUE THREAD

**Issue by areyance** [tachiyomiorg/website#876]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

adding an additional feature tied to "search other (installed) extension" for when your desired manga was not found in the sources u chose to pin

### Other details

this would make the existing option dual purpose ,serving as a sort of favourite/often used extension and if those didn't return a result u can with this get directed to searching in the other extensions u didn't pin as an in-depth or thorough advanced search

**Comment by alessandrojean** [comment]
Wrong repository, open an issue in the app repository instead.
