### ISSUE TITLE
Library rows keep on changing from 4 rows to 3 rows

### ISSUE THREAD

**Issue by Qhuel** [tachiyomiorg/website#884]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

I set my library to 4 rows but whenever i press any other button and then go back to the library it shows 3 rows then go back to 4 rows.

### Expected behavior

Library set to 4 rows should be the same after i press any other button 

### Actual behavior

Whenever i press any other button then go back to library it shows me 3 rows and then goes back to 4 rows

### Other details

https://user-images.githubusercontent.com/104735787/166162747-04f62be1-3b1e-4460-8f8c-e91f87186eac.mp4

**Comment by Seishirou101** [comment]
not the right repo.
