### ISSUE TITLE
I couldn't find the website in the app

### ISSUE THREAD

**Issue by Tadaningenda** [tachiyomiorg/website#910]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

https://www.mangasol.com/

Mangasol (arabic)

I couldn't find this website when i searched it 

### Expected behavior

It's a little big website that a expect to find it 

### Actual behavior

I surprised that it's not there

### Other details

Thank for taking your time

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues
