### ISSUE TITLE
Extension addition 

### ISSUE THREAD

**Issue by T0PMAX** [tachiyomiorg/website#956]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Plz add the "Luminous scans" extension to the app most  of manhwas/mangas/manhuas that are dropped by other Scanlation are in that site so plz ☺️

### Other details

[Luminous Scan](https://luminousscans.com/)

**Comment by arkon** [comment]
Wrong repo.
