### ISSUE TITLE
Saving panels of a manga straight to an SD card.

### ISSUE THREAD

**Issue by ashurxz** [tachiyomiorg/website#967]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

You get what i am saying, like downloading Manga chapters straight to an sd card, i would love to get a feature that makes it so all the panels automatically save to an SD card, please i look forward to it.

**Comment by loocool2** [comment]
I don't get what you're saying, and I don't think this issue belongs in the repo for the Tachiyomi website either. Please elaborate on what exactly you're asking about.

**Comment by haith4m** [comment]
I think they specifically meant that the when downloading manga, the panels get saved in an sd card ,if available.

**Comment by ashurxz** [comment]
See when your saving panels while reading manga, they go to your internal memory, not external, i wanted a feature to make it to go to external automatically

**Comment by arkon** [comment]
Why are people still commenting on this when it's not even in the right repo?

Also, no. The app simply saves it to whatever the system says is the place to save pictures.

**Comment by ashurxz** [comment]
Is there any way i can change that
